### ISSUE TITLE
Great Content But UAV seems not working

### ISSUE THREAD

**Issue by cloudyaaron** [necr0n/dcs-make-flyable#11]
UAVs seems controllable but not in the first person view

**Comment by necr0n** [comment]
Can reproduce for both MQ-1 and MQ-9. If a cockpit is required, which one would you choose? The free Su-25T?

**Comment by necr0n** [comment]
Tried uncommenting Shapes https://github.com/necr0n/dcs-make-flyable/blob/master/MQ-1A%20Predator/entry.lua#L49 to enable the default Su-25T cockpit which was disabled for immersion, didn't work, camera just rolls inside and then switches to F2 view.

From the dcs.log: LUA CPU usage is abnormally high, this could indicate a base game bug. I'll check what this error could mean.

```
2022-01-21 00:16:21.666 INFO    APP: MissionSpawn:spawnLocalPlayer 1,MQ-9 Reaper
2022-01-21 00:16:21.755 INFO    WORLDGENERAL: loaded from mission Scripts/World/birds.lua
2022-01-21 00:16:21.755 INFO    APP: dbox not found , skip
2022-01-21 00:16:21.821 INFO    LUA: Lua CPU usage: metric: average mission execution: 28.8893 %
```

**Comment by cloudyaaron** [comment]
I also make DCS mods, i believe this issue is caused by no crew is declared in the code. and that is a no fix if integration check is compulsury.

**Comment by fire310** [comment]
а как вообще тут ставить моды?

**Comment by necr0n** [comment]
@fire310 please open a separate issue, I think you've figured out by now.

Lately many cockpits/planes have been reworked, nothing we can easily fix.
