### ISSUE TITLE
Mig 31 keeps crashing the game

### ISSUE THREAD

**Issue by Spiond** [necr0n/dcs-make-flyable#12]
Hi, Thanks for making these awesome mods! Im playing on Open Beta 2.7 and I own FC3. The Mig 31, like all other aircraft didnt have the proper keybindings, so I copied the Su-33s Input into the Mig 31 Input. If I select the slot for the first time after mission start it works fine. Avionics, weapons and keybinds work flawlessly, however, as soon as I select a different slot like the Mig 23 and I try to get into the Mig 31 again the game crashes. Any Idea on how to fix it?

**Comment by necr0n** [comment]
Hi Spiond, thanks for reporting.

First, the script ps.bat should do the copy - you don't have to copy Inputs for all the planes if you run it and select correct DCS install folder .

Second - can't reproduce the issue with MiG-31, tried on 4YA server
[video](https://media.giphy.com/media/xN9spfGLek0tac5hjf/giphy.gif)
After crash, can you take a look at dcs.log (C:/Users/<your user>/Saved Games/DCS/dcs.log) - what are the last lines?
Did you try removing all other mods from your Mods folder, keeping only MiG-31?

Regards,
necr

**Comment by Spiond** [comment]
Ok, so I've reinstalled the mods and now it works. No crashes at all. Seems I took the wrong folder last time, since now it copied all the inputs right away. Thanks for the quick response, appreciate it. Cheers!
