### ISSUE TITLE
FC3 acnnot be find

### ISSUE THREAD

**Issue by SniexDejjtik** [necr0n/dcs-make-flyable#14]
when im cliking on the PS.bat it say it cannot find FC3 and i should do it manualy but IDK how :Y can someone help

**Comment by necr0n** [comment]
@SniexDejjtik the window gives you the prompt:

`Select DCS install folder, for example C:\Program Files (x86)\Steam\steamapps\common\DCSWorld`

You need to find it first, then you relaunch ps.bat and point it to your DCS folder.

**Comment by SniexDejjtik** [comment]
fixed it thx so much

**Comment by bombsnbiscuits** [comment]
I have DCS on my D drive but where do I install fc3? its on my C drive currently
it says 

The system cannot find the path specified.
Couldn't copy files from DCSWorld dir. Ensure FC3 is installed, restart the installer and choose DCSWorld directory manually.

**Comment by bombsnbiscuits** [comment]
Do I need FC3?

**Comment by necr0n** [comment]
> Do I need FC3?

Yes, most mods are FC3 based (before they got broken by the last patch.

> I have DCS on my D drive but where do I install fc3? its on my C drive currently it says

When you get FC3, it will be installed in your main directory on D:\
