### ISSUE TITLE
Great mod! but Su-30 does not have combat related key fields in controls menu. Any way to fix that issue? Thanks!

### ISSUE THREAD

**Issue by Danderg** [necr0n/dcs-make-flyable#8]
Thanks a ton for this magnificent mod! Unfortunately there are no control fields for Space, Enter, D, Shift+D etc. Aircraft is flyable but can`t be used in combat yet. I`m hoping there is a solution to that perhaps? Thanks again!
Cheers!

**Comment by necr0n** [comment]
hey!
did you run the setup script (ps.bat)?
It should copy input files from Su-27 folder of your Flaming Cliffs 3. You could copy and paste these files manually if you have Su-27 or FC3.
https://github.com/necr0n/dcs-make-flyable/blob/master/ps.bat#L94-L95

**Comment by Danderg** [comment]
Hi! I did run  .bat file. And pressed "Y" when prompted.
Could you elaborate more on copying Su-27 Files? Thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by necr0n** [comment]
What do you see in 
C:\Users\<your user>\Saved Games\DCS\Mods\aircraft\Su-30\Input\Su-30 ?
C:\Users\<your user>\Saved Games\DCS\Config\Input\su-30 ?

Do you own DCS FC3 or Su-27?

**Comment by Danderg** [comment]
Hi! i have FC3.
in C:\Users<your user>\Saved Games\DCS\Mods\aircraft\Su-30\Input\Su-30
 i have 2 folders(joystick, keyboard) and name. lua file.
in C:\Users<your user>\Saved Games\DCS\Config\Input\su-30     i have 4
folders(headtracker, joystick, keyboard, mouse) and modifiers.lua file.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Danderg** [comment]
I have a DCS mp server named EXERCISE RED FLAG and want to include
different flyable AI for people to enjoy them.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Danderg** [comment]
[image: Su-30noWeaponControlls.jpg]
There are no controls for weapons as you can see. I tried to manually copy
all files from Su-27 in config  and pasted/replaced in same config/ input
Su-30 files

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Danderg** [comment]
And for those controls that are available - when i try to manually assign
controls and double click in some field it doesn't let me to assign
controls for some reason.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by necr0n** [comment]
Ok, most likely the issue is non-matching saved input profile.
Please try to remove this folder:
C:\Users<your user>\Saved Games\DCS\Config\Input\su-30

After next start, you should have default Su-27 combat controls and then tune them as you wish.

**Comment by necr0n** [comment]
Did that help to solve the issue?

**Comment by Danderg** [comment]
no it didn't. Did it work for you?

пн, 19 Апр 2021, 23:08 Vladimir Chukov ***@***.***>:

**Comment by necr0n** [comment]
re-checked, it works for me (all Su-27 bindings are available, I can lock and fire).
I can't see your screenshot for some reason - it's not attached to the issue, can you reupload please?
It must be some other mod or saved config that's doing this.
Do other mods work - only this one doesn't? Are non-combat keys working fine (like G for gear down/up etc.)?

**Comment by Danderg** [comment]
Hi sorry for late reply. I will delete  all other mods and will try again.
Hope this time it will work.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by necr0n** [comment]
Hey, did it work? If it doesn't, ping me, I can jump in Discord for troubleshooting. Probably, with the release of new Su-30 pack this is now less relevant.

**Comment by Danderg** [comment]
> Hey, did it work? If it doesn't, ping me, I can jump in Discord for troubleshooting. Probably, with the release of new Su-30 pack this is now less relevant.

Sorry for such late reply. Managed to make it work) Thanks!

**Comment by Danderg** [comment]
I was trying to Fly your F-16A flyable mod and tried it to have F-15 cockpit and avionics. It seems i managed to do that after tweaking some files. But then i saw text file in the mod folder that said this:  "Because of missing Input profile, plane has only Su-25T inputs, same as F-4E.
That forces us to use Su-25T avionics with limited weapons support - at least AIM-120B/C, GBU-31/38 aren't working."
Does that mean that F-16A AI has different structure than Su-30? Why there can`t be no input profile for it ? Is there any way possible to create it so that in " ADJUST CONTROLS" window F-16A would appear instead of Su-25T?

**Comment by Danderg** [comment]
Sorry for such late reply. Yes) It does work now. Do you know why Su-30 has
its input profile and all other jet fighters do not have it? F-15E,F16A
F-18C and others have Su-25T input profiles. But why Su-30 is so special?

**Comment by necr0n** [comment]
You need to run setup script (ps.bat) that will copy the input profiles from default jets. The planes above have only AA or AG option and already existing input profiles, that's why they work.
